#!/usr/bin/env python
"""Concatenate the 4 torch-only Borissal v0.3 modules into one standalone file.

Only INTRA-PACKAGE relative imports (`from .`) are removed; stdlib/torch
imports are left in place (Python dedups repeated imports harmlessly). Run:
    uv run python scripts/build_standalone.py
Output: dist/borissal_v03.py
"""
import ast
import pathlib

SRC = pathlib.Path("autogaze/models/borissal")
ORDER = ["signals_v03.py", "configuration_borissal.py",
         "modeling_borissal.py", "adapters.py"]

HEADER = '''"""Borissal v0.5 -- single-file standalone saliency patch selector.

Auto-generated by scripts/build_standalone.py. Zero dependencies beyond
`torch` (+ Python stdlib). No trained weights.

    import torch
    from borissal_v05 import Borissal, BorissalConfig
    # v0_5: cube coherence + tunable motion_weight (V-JEPA/description downstream).
    #        v0_3()/v0_4() also available in the same file.
    sel = Borissal(BorissalConfig.v0_5()).select(
        torch.rand(1, 32, 3, 384, 384), gazing_ratio=0.25)
    # sel.keep_index -> (B, K) ascending flat token indices, -1 padded
"""

import math
from dataclasses import dataclass, field
from typing import Literal, Optional, Union

import torch
import torch.nn as nn
import torch.nn.functional as F
'''


def strip_module(fn: str) -> str:
    src = (SRC / fn).read_text()
    tree = ast.parse(src)
    lines = src.split("\n")
    drop = set()
    # drop the module docstring span
    if (tree.body and isinstance(tree.body[0], ast.Expr)
            and isinstance(tree.body[0].value, ast.Constant)):
        d = tree.body[0]
        for ln in range(d.lineno - 1, d.end_lineno):
            drop.add(ln)
    # drop only relative imports (from .x import ...) -- by AST, so docstring
    # text that merely starts with "from" is never touched
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.level and node.level > 0:
            for ln in range(node.lineno - 1, node.end_lineno):
                drop.add(ln)
    kept = [ln for i, ln in enumerate(lines) if i not in drop]
    return "\n".join(kept).strip("\n")


parts = [HEADER]
for fn in ORDER:
    parts.append(f"\n# {'=' * 70}\n# from {fn}\n# {'=' * 70}\n\n{strip_module(fn)}\n")

out = pathlib.Path("dist/borissal_v05.py")
out.parent.mkdir(exist_ok=True)
out.write_text("\n".join(parts))
print(f"wrote {out} ({len(out.read_text().splitlines())} lines)")
